version: '3'

services:
    postgres:
        image: postgres:13.3-alpine
        environment:
            POSTGRES_DB: subquery-node
            POSTGRES_PASSWORD: subquery-node
            POSTGRES_USER: subquery-node
        restart: always
        volumes:
            - postgres:/var/lib/postgresql/data
    node:
        build:
            args:
                NETWORK_ENDPOINT: wss://khala.phala.network/ws
                NETWORK_TYPEDEFS: khala
            context: ..
            dockerfile: docker/Dockerfile
        image: amphineko/phala-chainbridge-subql-node:latest-khala
        depends_on:
            - 'postgres'
        command:
            - -f=/app
            - --local
        environment:
            DB_DATABASE: subquery-node
            DB_HOST: postgres
            DB_PASS: subquery-node
            DB_PORT: 5432
            DB_USER: subquery-node
            NETWORK_ENDPOINT: wss://khala.phala.network/ws
            NETWORK_TYPEDEFS: khala
        restart: always
    query:
        image: onfinality/subql-query:latest
        command:
            - --name=app
            - --playground
        depends_on:
            - 'postgres'
            - 'node'
        environment:
            DB_DATABASE: subquery-node
            DB_HOST: postgres
            DB_PASS: subquery-node
            DB_PORT: 5432
            DB_USER: subquery-node
        ports:
            - 3100:3000
        restart: always

volumes:
    postgres:
